[build.env]
passthrough = [
    "CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS",
    "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS",
]

[target.x86_64-unknown-linux-musl]
[target.aarch64-unknown-linux-musl]
